/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.WindowConstants;

/**
 *
 * @author jeremy
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    double resultado = 0;
    String operacion = "", operacionBasica = "", operacionBasica2 = "", num1 = "", num2 = "";
    boolean banderaOperacion = true, banderaMulti = true, banderaDiv = true, banderaRes = true, bandera = true, val1 = false, val2 = false, banderaNumeros = true, banderaCalculo = true;

    DecimalFormat df = new DecimalFormat("#.0000");

    public Calculadora() {
        initComponents();

        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/CalculadoraIcon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_minimizar = new javax.swing.JLabel();
        label_Salir = new javax.swing.JLabel();
        label_imageTitle = new javax.swing.JLabel();
        label_title = new javax.swing.JLabel();
        btn_LimpiarTodo = new javax.swing.JButton();
        btn_CE = new javax.swing.JButton();
        btn_potencia = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        boton_acercaDe = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_coma = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_resultado = new javax.swing.JButton();
        btn_restar = new javax.swing.JButton();
        btn_sumar = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_dividir = new javax.swing.JButton();
        btn_sqrt = new javax.swing.JButton();
        btn_imc = new javax.swing.JButton();
        btn_pi = new javax.swing.JButton();
        txt_operacion = new javax.swing.JLabel();
        txt_resultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bg_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_minimizar.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        label_minimizar.setForeground(new java.awt.Color(255, 255, 0));
        label_minimizar.setText(".");
        label_minimizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(label_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 20, 30));

        label_Salir.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        label_Salir.setForeground(new java.awt.Color(255, 0, 0));
        label_Salir.setText(".");
        label_Salir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        label_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_SalirMouseClicked(evt);
            }
        });
        getContentPane().add(label_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 20, 30));

        label_imageTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CalculadoraIcon.png"))); // NOI18N
        label_imageTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_imageTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_imageTitleMouseClicked(evt);
            }
        });
        getContentPane().add(label_imageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        label_title.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_title.setForeground(new java.awt.Color(255, 255, 255));
        label_title.setText("Calculadora ©");
        label_title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label_title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_titleMouseClicked(evt);
            }
        });
        getContentPane().add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 40));

        btn_LimpiarTodo.setBackground(new java.awt.Color(50, 50, 50));
        btn_LimpiarTodo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_LimpiarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btn_LimpiarTodo.setText("\" \"");
        btn_LimpiarTodo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_LimpiarTodo.setContentAreaFilled(false);
        btn_LimpiarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LimpiarTodoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LimpiarTodoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LimpiarTodoMouseExited(evt);
            }
        });
        btn_LimpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_LimpiarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 40));

        btn_CE.setBackground(new java.awt.Color(50, 50, 50));
        btn_CE.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_CE.setForeground(new java.awt.Color(255, 255, 255));
        btn_CE.setText("CE");
        btn_CE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_CE.setContentAreaFilled(false);
        btn_CE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CEMouseExited(evt);
            }
        });
        btn_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CEActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 70, 40));

        btn_potencia.setBackground(new java.awt.Color(50, 50, 50));
        btn_potencia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_potencia.setForeground(new java.awt.Color(255, 255, 255));
        btn_potencia.setText("^");
        btn_potencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_potencia.setContentAreaFilled(false);
        btn_potencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_potenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_potenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_potenciaMouseExited(evt);
            }
        });
        btn_potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 70, 40));

        btn_C.setBackground(new java.awt.Color(50, 50, 50));
        btn_C.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        btn_C.setForeground(new java.awt.Color(255, 255, 255));
        btn_C.setText("c");
        btn_C.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_C.setContentAreaFilled(false);
        btn_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CMouseExited(evt);
            }
        });
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });
        getContentPane().add(btn_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 70, 40));

        boton_acercaDe.setBackground(new java.awt.Color(50, 50, 50));
        boton_acercaDe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_acercaDe.setForeground(new java.awt.Color(255, 255, 255));
        boton_acercaDe.setText("By:");
        boton_acercaDe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_acercaDe.setContentAreaFilled(false);
        boton_acercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_acercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_acercaDeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton_acercaDeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton_acercaDeMouseExited(evt);
            }
        });
        boton_acercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_acercaDeActionPerformed(evt);
            }
        });
        getContentPane().add(boton_acercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 70, 40));

        btn_0.setBackground(new java.awt.Color(50, 50, 50));
        btn_0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_0.setForeground(new java.awt.Color(255, 255, 255));
        btn_0.setText("0");
        btn_0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_0.setContentAreaFilled(false);
        btn_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_0MouseExited(evt);
            }
        });
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 70, 40));

        btn_coma.setBackground(new java.awt.Color(50, 50, 50));
        btn_coma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_coma.setForeground(new java.awt.Color(255, 255, 255));
        btn_coma.setText(".");
        btn_coma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_coma.setContentAreaFilled(false);
        btn_coma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_comaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_comaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_comaMouseExited(evt);
            }
        });
        btn_coma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_coma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 70, 40));

        btn_3.setBackground(new java.awt.Color(50, 50, 50));
        btn_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_3.setForeground(new java.awt.Color(255, 255, 255));
        btn_3.setText("3");
        btn_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_3.setContentAreaFilled(false);
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_3MouseExited(evt);
            }
        });
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 70, 40));

        btn_2.setBackground(new java.awt.Color(50, 50, 50));
        btn_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.setText("2");
        btn_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_2.setContentAreaFilled(false);
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_2MouseExited(evt);
            }
        });
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 70, 40));

        btn_1.setBackground(new java.awt.Color(50, 50, 50));
        btn_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_1.setForeground(new java.awt.Color(255, 255, 255));
        btn_1.setText("1");
        btn_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_1.setContentAreaFilled(false);
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_1MouseExited(evt);
            }
        });
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 70, 40));

        btn_4.setBackground(new java.awt.Color(50, 50, 50));
        btn_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_4.setForeground(new java.awt.Color(255, 255, 255));
        btn_4.setText("4");
        btn_4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_4.setContentAreaFilled(false);
        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_4MouseExited(evt);
            }
        });
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 70, 40));

        btn_5.setBackground(new java.awt.Color(50, 50, 50));
        btn_5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_5.setForeground(new java.awt.Color(255, 255, 255));
        btn_5.setText("5");
        btn_5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_5.setContentAreaFilled(false);
        btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_5MouseExited(evt);
            }
        });
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 70, 40));

        btn_6.setBackground(new java.awt.Color(50, 50, 50));
        btn_6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_6.setForeground(new java.awt.Color(255, 255, 255));
        btn_6.setText("6");
        btn_6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_6.setContentAreaFilled(false);
        btn_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_6MouseExited(evt);
            }
        });
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 70, 40));

        btn_9.setBackground(new java.awt.Color(50, 50, 50));
        btn_9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_9.setForeground(new java.awt.Color(255, 255, 255));
        btn_9.setText("9");
        btn_9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_9.setContentAreaFilled(false);
        btn_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_9MouseExited(evt);
            }
        });
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 70, 40));

        btn_8.setBackground(new java.awt.Color(50, 50, 50));
        btn_8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_8.setForeground(new java.awt.Color(255, 255, 255));
        btn_8.setText("8");
        btn_8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_8.setContentAreaFilled(false);
        btn_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_8MouseExited(evt);
            }
        });
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 70, 40));

        btn_7.setBackground(new java.awt.Color(50, 50, 50));
        btn_7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_7.setForeground(new java.awt.Color(255, 255, 255));
        btn_7.setText("7");
        btn_7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_7.setContentAreaFilled(false);
        btn_7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_7MouseExited(evt);
            }
        });
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 70, 40));

        btn_resultado.setBackground(new java.awt.Color(76, 194, 255));
        btn_resultado.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        btn_resultado.setForeground(new java.awt.Color(50, 50, 50));
        btn_resultado.setText("=");
        btn_resultado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_resultado.setBorderPainted(false);
        btn_resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resultadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_resultadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_resultadoMouseExited(evt);
            }
        });
        btn_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 70, 40));

        btn_restar.setBackground(new java.awt.Color(50, 50, 50));
        btn_restar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_restar.setForeground(new java.awt.Color(255, 255, 255));
        btn_restar.setText("-");
        btn_restar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_restar.setContentAreaFilled(false);
        btn_restar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_restarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_restarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_restarMouseExited(evt);
            }
        });
        btn_restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_restar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 70, 40));

        btn_sumar.setBackground(new java.awt.Color(50, 50, 50));
        btn_sumar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn_sumar.setForeground(new java.awt.Color(255, 255, 255));
        btn_sumar.setText("+");
        btn_sumar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_sumar.setContentAreaFilled(false);
        btn_sumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sumarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sumarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sumarMouseExited(evt);
            }
        });
        btn_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 70, 40));

        btn_multiplicar.setBackground(new java.awt.Color(50, 50, 50));
        btn_multiplicar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btn_multiplicar.setForeground(new java.awt.Color(255, 255, 255));
        btn_multiplicar.setText("X");
        btn_multiplicar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_multiplicar.setContentAreaFilled(false);
        btn_multiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_multiplicarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_multiplicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_multiplicarMouseExited(evt);
            }
        });
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_multiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 70, 40));

        btn_dividir.setBackground(new java.awt.Color(50, 50, 50));
        btn_dividir.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        btn_dividir.setForeground(new java.awt.Color(255, 255, 255));
        btn_dividir.setText("÷");
        btn_dividir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_dividir.setContentAreaFilled(false);
        btn_dividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dividirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dividirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dividirMouseExited(evt);
            }
        });
        btn_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dividirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 70, 40));

        btn_sqrt.setBackground(new java.awt.Color(50, 50, 50));
        btn_sqrt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_sqrt.setForeground(new java.awt.Color(255, 255, 255));
        btn_sqrt.setText("√");
        btn_sqrt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_sqrt.setContentAreaFilled(false);
        btn_sqrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sqrtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sqrtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sqrtMouseExited(evt);
            }
        });
        btn_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqrtActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 70, 40));

        btn_imc.setBackground(new java.awt.Color(50, 50, 50));
        btn_imc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_imc.setForeground(new java.awt.Color(255, 255, 255));
        btn_imc.setText("IMC");
        btn_imc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_imc.setContentAreaFilled(false);
        btn_imc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_imcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_imcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_imcMouseExited(evt);
            }
        });
        btn_imc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imcActionPerformed(evt);
            }
        });
        getContentPane().add(btn_imc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 40));

        btn_pi.setBackground(new java.awt.Color(50, 50, 50));
        btn_pi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_pi.setForeground(new java.awt.Color(255, 255, 255));
        btn_pi.setText("π");
        btn_pi.setActionCommand("%");
        btn_pi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_pi.setContentAreaFilled(false);
        btn_pi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_piMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_piMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_piMouseExited(evt);
            }
        });
        btn_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_piActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 40));

        txt_operacion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_operacion.setForeground(new java.awt.Color(153, 153, 153));
        txt_operacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(txt_operacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 40));

        txt_resultado.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        txt_resultado.setForeground(new java.awt.Color(255, 255, 255));
        txt_resultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_resultado.setText("0");
        getContentPane().add(txt_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 310, -1));

        bg_area.setEditable(false);
        bg_area.setBackground(new java.awt.Color(32, 32, 32));
        bg_area.setColumns(20);
        bg_area.setRows(5);
        jScrollPane1.setViewportView(bg_area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 325, 533));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_piMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_piMouseClicked

    }//GEN-LAST:event_btn_piMouseClicked

    private void btn_piMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_piMouseEntered
        btn_pi.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_piMouseEntered

    private void btn_piMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_piMouseExited
        btn_pi.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_piMouseExited

    private void btn_imcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_imcMouseClicked

    }//GEN-LAST:event_btn_imcMouseClicked

    private void btn_imcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_imcMouseEntered
        btn_imc.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_imcMouseEntered

    private void btn_imcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_imcMouseExited
        btn_imc.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_imcMouseExited

    private void btn_sqrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sqrtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sqrtMouseClicked

    private void btn_sqrtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sqrtMouseEntered
        btn_sqrt.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_sqrtMouseEntered

    private void btn_sqrtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sqrtMouseExited
        btn_sqrt.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_sqrtMouseExited

    private void btn_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqrtActionPerformed
        if (bandera) {
            operacion = "sqrt";
            txt_resultado.setText("0");
            Resultado(txt_resultado.getText());
            bandera = false;
        } else {
            Limpiar();
            txt_operacion.setText("");
            txt_resultado.setText("0");
        }
    }//GEN-LAST:event_btn_sqrtActionPerformed

    private void btn_dividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dividirMouseClicked

    }//GEN-LAST:event_btn_dividirMouseClicked

    private void btn_dividirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dividirMouseEntered
        btn_dividir.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_dividirMouseEntered

    private void btn_dividirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dividirMouseExited
        btn_dividir.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_dividirMouseExited

    private void btn_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dividirActionPerformed
        dividir(txt_resultado.getText());
    }//GEN-LAST:event_btn_dividirActionPerformed

    private void btn_multiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_multiplicarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_multiplicarMouseClicked

    private void btn_multiplicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_multiplicarMouseEntered
        btn_multiplicar.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_multiplicarMouseEntered

    private void btn_multiplicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_multiplicarMouseExited
        btn_multiplicar.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_multiplicarMouseExited

    private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
        multiplicar(txt_resultado.getText());
    }//GEN-LAST:event_btn_multiplicarActionPerformed

    private void btn_sumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sumarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sumarMouseClicked

    private void btn_sumarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sumarMouseEntered
        btn_sumar.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_sumarMouseEntered

    private void btn_sumarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sumarMouseExited
        btn_sumar.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_sumarMouseExited

    private void btn_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumarActionPerformed
        suma(txt_resultado.getText());
    }//GEN-LAST:event_btn_sumarActionPerformed

    private void btn_restarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_restarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_restarMouseClicked

    private void btn_restarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_restarMouseEntered
        btn_restar.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_restarMouseEntered

    private void btn_restarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_restarMouseExited
        btn_restar.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_restarMouseExited

    private void btn_restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restarActionPerformed
        resta(txt_resultado.getText());
    }//GEN-LAST:event_btn_restarActionPerformed

    private void btn_resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resultadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resultadoMouseClicked

    private void btn_resultadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resultadoMouseEntered
        btn_resultado.setBackground(new Color(100, 210, 255));
    }//GEN-LAST:event_btn_resultadoMouseEntered

    private void btn_resultadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resultadoMouseExited
        btn_resultado.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_resultadoMouseExited

    private void btn_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultadoActionPerformed

        Resultado(txt_resultado.getText());
    }//GEN-LAST:event_btn_resultadoActionPerformed

    private void btn_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MouseClicked

    }//GEN-LAST:event_btn_9MouseClicked

    private void btn_9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MouseEntered
        btn_9.setBackground(Color.orange);
    }//GEN-LAST:event_btn_9MouseEntered

    private void btn_9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_9MouseExited
        btn_9.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_9MouseExited

    private void btn_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_8MouseClicked

    private void btn_8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MouseEntered
        btn_8.setBackground(Color.orange);
    }//GEN-LAST:event_btn_8MouseEntered

    private void btn_8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_8MouseExited
        btn_8.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_8MouseExited

    private void btn_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4MouseClicked

    private void btn_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseEntered
        btn_4.setBackground(Color.orange);
    }//GEN-LAST:event_btn_4MouseEntered

    private void btn_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MouseExited
        btn_4.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_4MouseExited

    private void btn_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_5MouseClicked

    private void btn_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseEntered
        btn_5.setBackground(Color.orange);
    }//GEN-LAST:event_btn_5MouseEntered

    private void btn_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_5MouseExited
        btn_5.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_5MouseExited

    private void btn_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_6MouseClicked

    private void btn_6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MouseEntered
        btn_6.setBackground(Color.orange);
    }//GEN-LAST:event_btn_6MouseEntered

    private void btn_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_6MouseExited
        btn_6.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_6MouseExited

    private void btn_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_3MouseClicked

    private void btn_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MouseEntered
        btn_3.setBackground(Color.orange);
    }//GEN-LAST:event_btn_3MouseEntered

    private void btn_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MouseExited
        btn_3.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_3MouseExited

    private void btn_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_2MouseClicked

    private void btn_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseEntered
        btn_2.setBackground(Color.orange);
    }//GEN-LAST:event_btn_2MouseEntered

    private void btn_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MouseExited
        btn_2.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_2MouseExited

    private void btn_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1MouseClicked

    private void btn_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MouseEntered
        btn_1.setBackground(Color.orange);
    }//GEN-LAST:event_btn_1MouseEntered

    private void btn_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MouseExited
        btn_1.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_1MouseExited

    private void boton_acercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_acercaDeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_acercaDeMouseClicked

    private void boton_acercaDeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_acercaDeMouseEntered
        boton_acercaDe.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_boton_acercaDeMouseEntered

    private void boton_acercaDeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_acercaDeMouseExited
        boton_acercaDe.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_boton_acercaDeMouseExited

    private void btn_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_0MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_0MouseClicked

    private void btn_0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_0MouseEntered
        btn_0.setBackground(Color.orange);
    }//GEN-LAST:event_btn_0MouseEntered

    private void btn_0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_0MouseExited
        btn_0.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_0MouseExited

    private void btn_comaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_comaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_comaMouseClicked

    private void btn_comaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_comaMouseEntered
        btn_coma.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_comaMouseEntered

    private void btn_comaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_comaMouseExited
        btn_coma.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_comaMouseExited

    private void btn_LimpiarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LimpiarTodoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LimpiarTodoMouseClicked

    private void btn_LimpiarTodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LimpiarTodoMouseEntered
        btn_LimpiarTodo.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_LimpiarTodoMouseEntered

    private void btn_LimpiarTodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LimpiarTodoMouseExited
        btn_LimpiarTodo.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_LimpiarTodoMouseExited

    private void btn_CEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CEMouseClicked

    private void btn_CEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CEMouseEntered
        btn_CE.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_CEMouseEntered

    private void btn_CEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CEMouseExited
        btn_CE.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_CEMouseExited

    private void btn_potenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_potenciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_potenciaMouseClicked

    private void btn_potenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_potenciaMouseEntered
        btn_potencia.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_potenciaMouseEntered

    private void btn_potenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_potenciaMouseExited
        btn_potencia.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_potenciaMouseExited

    private void btn_potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potenciaActionPerformed
        if (bandera) {
            operacion = "potencia";
            txt_resultado.setText("0");
            Resultado(txt_resultado.getText());
            bandera = false;
        } else {
            Limpiar();
            txt_operacion.setText("");
            txt_resultado.setText("0");
        }
    }//GEN-LAST:event_btn_potenciaActionPerformed

    private void btn_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CMouseClicked

    }//GEN-LAST:event_btn_CMouseClicked

    private void btn_CMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CMouseEntered
        btn_C.setBackground(Color.decode("#4cc2ff"));
    }//GEN-LAST:event_btn_CMouseEntered

    private void btn_CMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CMouseExited
        btn_C.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_CMouseExited

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        Borrar("Uno");
    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_LimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarTodoActionPerformed
        limpiarResultado();
    }//GEN-LAST:event_btn_LimpiarTodoActionPerformed

    private void btn_7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MouseExited
        btn_7.setBackground(Color.decode("#323232"));
    }//GEN-LAST:event_btn_7MouseExited

    private void btn_7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MouseEntered
        btn_7.setBackground(Color.orange);
    }//GEN-LAST:event_btn_7MouseEntered

    private void btn_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_7MouseClicked

    private void label_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_SalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_label_SalirMouseClicked

    private void label_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimizarMouseClicked
        this.setState(ICONIFIED);
        Limpiar();
    }//GEN-LAST:event_label_minimizarMouseClicked

    private void label_imageTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_imageTitleMouseClicked
        new AcercaDe().setVisible(true);
    }//GEN-LAST:event_label_imageTitleMouseClicked

    private void btn_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_piActionPerformed
        if (bandera) {
            txt_operacion.setText("PI");
            txt_resultado.setText("" + Math.PI);
            bandera = false;
        } else {
            Limpiar();
            txt_operacion.setText("");
            txt_resultado.setText("0");
        }

    }//GEN-LAST:event_btn_piActionPerformed

    private void btn_imcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imcActionPerformed

        if (bandera) {
            operacion = "IMC";
            txt_resultado.setText("0");
            Resultado(txt_resultado.getText());
            bandera = false;
        } else {
            Limpiar();
            txt_operacion.setText("");
            txt_resultado.setText("0");
        }


    }//GEN-LAST:event_btn_imcActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        IngresarNumero("7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        IngresarNumero("8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        IngresarNumero("9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        IngresarNumero("4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        IngresarNumero("5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        IngresarNumero("6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        IngresarNumero("3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        IngresarNumero("2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        IngresarNumero("1");
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        IngresarNumero("0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CEActionPerformed
        Borrar("todo");
    }//GEN-LAST:event_btn_CEActionPerformed

    private void btn_comaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comaActionPerformed
        IngresarNumero(".");
    }//GEN-LAST:event_btn_comaActionPerformed

    private void label_titleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_titleMouseClicked

    }//GEN-LAST:event_label_titleMouseClicked

    private void boton_acercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_acercaDeActionPerformed
        new AcercaDe().setVisible(true);
    }//GEN-LAST:event_boton_acercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public void IngresarNumero(String num) {
        String texto = txt_resultado.getText();
        bandera = true;

        int cc = contarCaracteres(texto, '.');

        if (operacionBasica == "") {

            if (texto.charAt(0) == '0' && num.equalsIgnoreCase("0") || num.equalsIgnoreCase(".") && cc == 1) {

            } else if (texto.charAt(0) == '0' && !num.equalsIgnoreCase(".") && cc == 0 || texto.charAt(0) == 0 && num == ".") {
                texto = num;

            } else if (texto.charAt(0) != '0' || num.equalsIgnoreCase(".") && cc == 0) {
                texto += num;
            } else {
                texto += num;
            }

            txt_resultado.setText(texto);
        } else {
            txt_resultado.setText(num);
            operacionBasica2 = operacionBasica;
            operacionBasica = "";

        }

    }

    public void suma(String num) {

        if (bandera) {
            resultado = resultado + Double.parseDouble(num);
            operacionBasica = "suma";

            txt_operacion.setText(resultado + " + ");
            txt_resultado.setText(resultado + "");
            bandera = false;
        }
    }

    public void resta(String num) {

        if (bandera) {

            if (banderaRes) {
                resultado = Double.parseDouble(num);
                banderaRes = false;

            } else {
                resultado = resultado - Double.parseDouble(num);
            }

            operacionBasica = "resta";

            txt_operacion.setText(resultado + " - ");
            txt_resultado.setText(resultado + "");
            bandera = false;
        }

    }

    public void multiplicar(String num) {

        if (bandera) {

            if (banderaMulti) {
                resultado = Double.parseDouble(num);
                banderaMulti = false;

            } else {
                resultado = resultado * Double.parseDouble(num);
            }

            operacionBasica = "multiplicar";

            txt_operacion.setText(resultado + " x ");
            txt_resultado.setText(resultado + "");
            bandera = false;
        }

    }

    public void dividir(String num) {

        if (bandera) {

            if (banderaDiv) {
                resultado = Double.parseDouble(num);
                banderaDiv = false;

            } else {
                resultado = resultado / Double.parseDouble(num);
            }

            operacionBasica = "dividir";

            txt_operacion.setText(resultado + " ÷ ");
            txt_resultado.setText(resultado + "");
            bandera = false;
        }

    }

    public void Limpiar() {
        val1 = false;
        bandera = true;
        banderaCalculo = true;
        val2 = false;

        operacion = "";
        resultado = 0;
    }

    public void Borrar(String borra) {

        if (borra.equalsIgnoreCase("todo")) {

            txt_resultado.setText("0");

        } else {

            if (txt_resultado.getText().length() == 1) {
                txt_resultado.setText("0");

            } else {

                String texto = txt_resultado.getText();
                texto = texto.substring(0, texto.length() - 1);

                txt_resultado.setText(texto);
            }

        }
    }

    public void Resultado(String num) {

        if (operacion.equalsIgnoreCase("IMC")) {

            if (banderaCalculo) {
                txt_operacion.setText("Ingrese su talla: ");

                banderaCalculo = false;
            } else if (val1) {

                num2 = num;
                val2 = true;

            } else {
                num1 = num;
                txt_resultado.setText("0");
                txt_operacion.setText("Ingrese su peso:");
                val1 = true;
            }

            if (val2) {

                txt_operacion.setText("IMC:");
                double dou_talla = Double.parseDouble(num1);
                double dou_peso = Double.parseDouble(num2);

                resultado = dou_peso / (dou_talla * dou_talla);

                txt_resultado.setText("" + df.format(resultado));

                Limpiar();

            }

        } else if (operacion.equalsIgnoreCase("Potencia")) {

            if (banderaCalculo) {
                txt_operacion.setText("Ingrese la base: ");

                banderaCalculo = false;
            } else if (val1) {

                num2 = num;
                val2 = true;

            } else {
                num1 = num;
                txt_resultado.setText("0");
                txt_operacion.setText("Ingrese el exponente:");
                val1 = true;
            }

            if (val2) {

                txt_operacion.setText("Potencia:");
                double dou_base = Double.parseDouble(num1);
                double dou_exponente = Double.parseDouble(num2);

                resultado = Math.pow(dou_base, dou_exponente);

                txt_resultado.setText("" + df.format(resultado));

                Limpiar();

            }
        } else if (operacion.equalsIgnoreCase("sqrt")) {
            if (banderaCalculo) {
                txt_operacion.setText("Ingrese el numero: ");

                banderaCalculo = false;

            } else {

                double raizNum = Double.parseDouble(num);

                if (raizNum > 0) {

                    txt_operacion.setText("Raiz:");

                    resultado = Math.sqrt(raizNum);

                    txt_resultado.setText("" + df.format(resultado));

                    Limpiar();

                } else {
                    txt_operacion.setText("");
                    txt_resultado.setText("No se pudo sacar la raiz cuadrada, vuelve a intentar");
                    Limpiar();
                }

            }

        } else if (operacionBasica2.equalsIgnoreCase("suma")) {

            bandera = true;

            if (banderaNumeros) {
                txt_operacion.setText(txt_operacion.getText() + num + " = ");
                banderaNumeros = false;

            } else {
                txt_operacion.setText(resultado + " + " + num + " = ");
            }
            txt_resultado.setText(resultado + Double.parseDouble(num) + "");

        } else if (operacionBasica2.equalsIgnoreCase("resta")) {
            bandera = true;

            if (banderaNumeros) {
                txt_operacion.setText(txt_operacion.getText() + num + " = ");
                banderaNumeros = false;

            } else {
                txt_operacion.setText(resultado + " - " + num + " = ");
            }
            txt_resultado.setText(resultado - Double.parseDouble(num) + "");

        } else if (operacionBasica2.equalsIgnoreCase("multiplicar")) {
            bandera = true;

            if (banderaNumeros) {
                txt_operacion.setText(txt_operacion.getText() + num + " = ");
                banderaNumeros = false;

            } else {
                txt_operacion.setText(resultado + " x " + num + " = ");
            }
            txt_resultado.setText(resultado * Double.parseDouble(num) + "");

        } else if (operacionBasica2.equalsIgnoreCase("dividir")) {

            try {
                bandera = true;

                if (banderaNumeros) {
                    txt_operacion.setText(txt_operacion.getText() + num + " = ");
                    banderaNumeros = false;

                } else {
                    txt_operacion.setText(resultado + " ÷ " + num + " = ");
                }
                txt_resultado.setText(resultado / Double.parseDouble(num) + "");

                banderaOperacion = true;

            } catch (NumberFormatException e) {
                txt_operacion.setText("Numero Incorrecto: ");

                if (num.equalsIgnoreCase("0")) {
                    txt_resultado.setText("No se puede dividir entre cero");
                } else {
                    txt_resultado.setText("Division incorrecta");
                }
                Limpiar();
            }
        }
    }

    public void limpiarResultado() {

        txt_resultado.setText("0");

        banderaDiv = true;
        banderaMulti = true;
        banderaRes = true;
        txt_operacion.setText("");
        Limpiar();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bg_area;
    private javax.swing.JButton boton_acercaDe;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_CE;
    private javax.swing.JButton btn_LimpiarTodo;
    private javax.swing.JButton btn_coma;
    private javax.swing.JButton btn_dividir;
    private javax.swing.JButton btn_imc;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_pi;
    private javax.swing.JButton btn_potencia;
    private javax.swing.JButton btn_restar;
    private javax.swing.JButton btn_resultado;
    private javax.swing.JButton btn_sqrt;
    private javax.swing.JButton btn_sumar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_Salir;
    private javax.swing.JLabel label_imageTitle;
    private javax.swing.JLabel label_minimizar;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel txt_operacion;
    private javax.swing.JLabel txt_resultado;
    // End of variables declaration//GEN-END:variables

    public static int contarCaracteres(String cadena, char caracter) {
        int posicion, contador = 0;

        posicion = cadena.indexOf(caracter);
        while (posicion != -1) {
            contador++;

            posicion = cadena.indexOf(caracter, posicion + 1);
        }
        return contador;
    }
}
